name: coc-helper CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [12, 14]

    env:
      NODE_ENV: test

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Install pnpm
        run: |
          npm install -g pnpm
      - uses: actions/checkout@v2
      - name: Install Packages
        run: pnpm install
      - name: Lint
        run: pnpm run lint
      - name: Install vim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: v0.4.3
      - name: Run unit tests
        env:
          NODE_ENV: test
        run: pnpm test
