name: coc-helper CI

on:
  push:
    branches:
      - master
      - develop
  pull_request:
    branches:
      - master
      - develop

jobs:
  test:
    runs-on: ${{ matrix.os }}

    strategy:
      fail-fast: false
      matrix:
        os: [ubuntu-latest, windows-latest]
        node-version: [14, 16]

    env:
      NODE_ENV: test

    steps:
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v2
        with:
          node-version: ${{ matrix.node-version }}
      - name: Set git
        run: |
          git config --global core.autocrlf false
      - uses: actions/checkout@v2
      - name: Install Packages
        run: yarn install
      - name: Lint
        run: yarn run lint
      - name: Install vim
        uses: rhysd/action-setup-vim@v1
        with:
          neovim: true
          version: v0.7.0
      - name: Run unit tests
        env:
          NODE_ENV: test
        run: yarn test
